### ISSUE TITLE
Errors in buildcal

### ISSUE THREAD

**Issue by bege5080** [PrincetonUniversity/charis-dep#7]
I followed the documentation to successfully install gcc5 (via macports) and the DRP with no errors, but then got the following errors when trying to run buildcal:

gaia:reduced_data BGerard$ buildcal ../CRSA00018948.fits ../CRSA0001895[2-9].fits
Traceback (most recent call last):
  File "/Users/BGerard/anaconda2/bin/buildcal", line 4, in <module>
    __import__('pkg_resources').run_script('charis==1.0.0', 'buildcal')
  File "/Users/BGerard/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/BGerard/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/BGerard/anaconda2/lib/python2.7/site-packages/charis-1.0.0-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/buildcal", line 26, in <module>
    
  File "build/bdist.macosx-10.6-x86_64/egg/charis/primitives/__init__.py", line 2, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/charis/primitives/fit_psflets.py", line 11, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/charis/primitives/matutils.py", line 7, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/charis/primitives/matutils.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/BGerard/Library/Caches/Python-Eggs/charis-1.0.0-py2.7-macosx-10.6-x86_64.egg-tmp/charis/primitives/matutils.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/BGerard/Library/Caches/Python-Eggs/charis-1.0.0-py2.7-macosx-10.6-x86_64.egg-tmp/charis/primitives/matutils.so
  Expected in: flat namespace
 in /Users/BGerard/Library/Caches/Python-Eggs/charis-1.0.0-py2.7-macosx-10.6-x86_64.egg-tmp/charis/primitives/matutils.so

**Comment by bege5080** [comment]
resolved by changing the install to the default c compiler:

python setup.py install
